version: "3.10"

services:
  djangoapp:
    container_name: djangoapp
    build: .
    volumes:
      - .:/django
    ports:
      - 8000:8000
    image: app:django
    environment:
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_DB=postgres
      - PG_HOST=db
      - PG_PORT=5432
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}