# Generated by Django 4.1 on 2023-04-17 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0006_alter_cartitem_cart"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orders",
            name="cart_items",
        ),
        migrations.AddField(
            model_name="orders",
            name="cart_items",
            field=models.TextField(null=True),
        ),
    ]
