# Generated by Django 4.1 on 2023-04-17 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0007_remove_orders_cart_items_orders_cart_items"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders",
            name="cart_items",
            field=models.TextField(default=""),
        ),
    ]
