# Generated by Django 4.1 on 2023-05-10 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0008_alter_orders_cart_items"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="description",
        ),
        migrations.RemoveField(
            model_name="category",
            name="image",
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.URLField(blank=True),
        ),
    ]
